name: Check SemVer

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-semver:
    concurrency:
      group: '${{ github.workflow }}'
      cancel-in-progress: true
      
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
        with:
          fetch-depth: 0

      - uses: ./
        with:
          check-minor-version: true
